### ISSUE TITLE
Pretrained Weights

### ISSUE THREAD

**Issue by ldkong1205** [md4all/md4all#1]
Hi @sgasperini and @morbi25, thanks for open-sourcing this interesting work!

Could you provide the pretrained weights for the self-supervised models? Thanks!

**Comment by sgasperini** [comment]
Hi @ldkong1205, thank you for your interest in our work!

You can find the pretrained weights [here](https://drive.google.com/drive/folders/1nylOZitf8P33vlq-TKEcGte0FCQQ1wR5?usp=sharing).
The instructions to load them are [here in the readme](https://github.com/md4all/md4all#evaluation-and-pre-trained-models).
We will update the readme to make it more explicit.

Feel free to let us know if you have more questions. Thank you!

**Comment by ldkong1205** [comment]
> Hi @ldkong1205, thank you for your interest in our work!
> 
> You can find the pretrained weights [here](https://drive.google.com/drive/folders/1nylOZitf8P33vlq-TKEcGte0FCQQ1wR5?usp=sharing). The instructions to load them are [here in the readme](https://github.com/md4all/md4all#evaluation-and-pre-trained-models). We will update the readme to make it more explicit.
> 
> Feel free to let us know if you have more questions. Thank you!

Hi @sgasperini, thanks a lot for your prompt reply and instructions! Congratulations on the acceptance ~
