### ISSUE TITLE
Where to get the txts in extrinsics?

### ISSUE THREAD

**Issue by Amor-ZYF** [md4all/md4all#11]
How can I get the files in the folder robotcar/extrinsics? I thought that I could get them from the RobotCar Dataset but I didn't find out the location of these files. Can you point out where I can find or download these files so that I can do the step 5 in Dataset->RobotCar. Thanks a lot!

**Comment by sgasperini** [comment]
Hi @AmorDemon,

Thank you for your interest in our work!

For RobotCar, you can find the `*.txt` content of the `extrinsics` folder in the SDK of the dataset: [here](https://github.com/ori-mrg/robotcar-dataset-sdk/tree/16ce3329223ca418fe5106277b91aea8d9b672b2/extrinsics). That same repository also contains the other files that should help you set up your filesystem to be similar to the one in the screenshot we provided in the readme.

You are correct that this needed to be clarified in the readme. So, we are updating it accordingly.

**Comment by LZL-CS** [comment]
> Hi @AmorDemon,
> 
> Thank you for your interest in our work!
> 
> For RobotCar, you can find the `*.txt` content of the `extrinsics` folder in the SDK of the dataset: [here](https://github.com/ori-mrg/robotcar-dataset-sdk/tree/16ce3329223ca418fe5106277b91aea8d9b672b2/extrinsics). That same repository also contains the other files that should help you set up your filesystem to be similar to the one in the screenshot we provided in the readme.
> 
> You are correct that this needed to be clarified in the readme. So, we are updating it accordingly.

Hi @sgasperini, for `*.txt` in `extrinsics` in the RobotCar dataset, such as `ins.txt`, does it mean transformation from `ins` to `stereo`, where `stereo's` coordinate is the same as vehicle coordinate?

**Comment by sgasperini** [comment]
Hi @LZL-CS,

I believe the best place to find answers to this is the documentation of the RobotCar dataset ([see here](https://robotcar-dataset.robots.ox.ac.uk/documentation/)) and their SDK ([see here](https://github.com/ori-mrg/robotcar-dataset-sdk/tree/16ce3329223ca418fe5106277b91aea8d9b672b2/python)). It should be as you indicated.

In isolation, these transformation matrices can be confusing, but one can always check the documentation and visualize things to ensure the transformations operate as expected. Have a look, for example, at the `project_laser_into_camera.py` file of the SDK ([here](https://github.com/ori-mrg/robotcar-dataset-sdk/blob/16ce3329223ca418fe5106277b91aea8d9b672b2/python/project_laser_into_camera.py)) where they project the LiDAR point cloud to the image. That should give you insights on how the transforms were intended.

If you have more specific questions on the dataset, you can ask them to the RobotCar authors directly, as they curated the dataset themselves.

**Comment by Amor-ZYF** [comment]
Hi @sgasperini ,
I tried to remove the velocity loss for the training of your baseline on RobotCar to see how this loss affects the final results, so I set the _C.LOSS.VELOCITY_WEIGHT = 0.0 in config.py, then after training the quantitative result is completely strange.
![error result](https://github.com/md4all/md4all/assets/40883785/38277436-3b51-4e0a-bf22-a867fa87722a)

Are there any other codes should I change to remove the influence of the velocity loss? Thanks a lot for your reply!

**Comment by sgasperini** [comment]
Hi @AmorDemon,

Thank you for your question.

By excluding the weak velocity supervision, what is left is essentially a Monodepth2 model. 

Please consider that the velocity loss from PackNet-SfM enables scale awareness. So, without scale awareness, the relevant quantitative results are the `_gt` or `_pp_gt` values. Specifically, the `*gt` values are scaled according to the LiDAR ground truth data. For more information about the differences between the plain, `pp`, `gt`, and `pp_gt` values in the evaluation output, we refer to the 3rd point of issue #8.

Your screenshot shows that the `pp_gt` values for `abs_rel` and the other metrics you obtained align with the ones we reported in Table 2 for Monodepth2 on RobotCar. So, I do not see anything strange there; your results look good, considering you trained Monodepth2.

I believe you were looking at the values without `gt`. I hope this answer helps clear up your doubts.

**Comment by Amor-ZYF** [comment]
It's very clear now. Thanks for your reply!
