### ISSUE TITLE
Question of generateing the adverse image

### ISSUE THREAD

**Issue by newaccountfor** [md4all/md4all#16]
Hello, thankyou for your meaningful work and I encontered some problems when generateing the adverse images. I only want to generate adverse image only from the day_clear images, but in nuscenes datasets there are some real night and rain images which are unexpect in the genearting process. So how can I exclude them from the genearting process? I noticed that there are weather tokens for different scenes, but I fail to build the correlation between the weather condition to every input images.

**Comment by newaccountfor** [comment]
Sorry for bothering. I've solved this problem by output the day_clear images to another folder, so the generating network can simply read the whole folder.

**Comment by sgasperini** [comment]
Hi @newaccountfor,
Thank you for your interest in our work! Great to hear you could already address the problem.
Then, I'm closing this issue.
Best regards
