### ISSUE TITLE
Issues related to baseline training and evaluation

### ISSUE THREAD

**Issue by zsh1223** [md4all/md4all#26]
Which of the day, night, clear, rain, day clear, day rain, night clear, and night rain datasets were used for baseline training. (Baseline refers to the teacher model that generates training signals).
As stated in the paper, this baseline should be a model trained through self supervised learning using daytime images. But why is the evaluation of scenarios such as day, night, clear, rain, day clear, day rain, night clear, and night rain only tested on them?
Looking forward to your answer.
![Uploading image.png…]()

**Comment by sgasperini** [comment]
Hi @zsh1223, thanks again for your interest. For nuScenes, the baseline was trained only on day_clear, which represents the images at daytime without rain. For RobotCar, the baseline was trained only on day, which means daytime (there was no rain set).
We hope this helps!

**Comment by zsh1223** [comment]
Thanks for your prompt and detailed reply! I am closing this issue.

**Comment by zsh1223** [comment]
Thanks for your prompt and detailed reply! I am closing this issue.
