### ISSUE TITLE
About a3_gt and a3_pp_gt

### ISSUE THREAD

**Issue by zsh1223** [md4all/md4all#27]
I want to know how these two indicators are calculated. In your def computeddepth_metrics (gt, pred, weather, metrics, mode, min_depth, max_depth, useugtscale=True): function, calculate a1, a2, and a3 using pred=depth_pp/depth.
This indicates that you have used either the predicted depth map (depth) or the flipped enhanced depth map (depth_pp). But please help me point out how a3_gt and a3_pp_gt are calculated in the program. And tell me their significance.
I guess the meaning of _gt is the accuracy of the original data file after being limited by the depth range.
The meaning of _pp_gt is the accuracy of the original data file after depth range limitation and flipping enhancement.
But I can't find their implementation in your program.
Please teach me, thank you very much

**Comment by sgasperini** [comment]
Hi @zsh1223,

The metrics delta^1, delta^2, and delta^3 are commonly used in evaluating depth estimation. In our code, they appear as a1, a2, and a3, respectively.

They are referred to as accuracy metrics as they all calculate the percentage of pixels where the ratio between the predicted depth and the true depth (or vice versa) is within a certain threshold. What changes between the 3 metrics is the threshold:
- for delta^1, the threshold is 1.25 for the ratios, meaning within 25% of one another.
- for delta^2, the threshold is 1.25^2 (squared), which is 1.5625, meaning within 56.25% of one another.
- for delta^3, the threshold is 1.25^3 (cubed), which is 1.953125, meaning within 95.3125% of one another.

The true depth is the ground truth from the LiDAR sensor.
delta^3 is computed as a3 at the following line: https://github.com/md4all/md4all/blob/1cb9300fc08d4a44d1f1d8faea96f0d4ca5bb1dc/utils/depth.py#L235


Regarding the `_pp_gt` and `_gt` naming, please check the 3rd point of issue #8 where we described it.

We hope this helps clear your doubts!

**Comment by zsh1223** [comment]
I know that a1 is calculated by pred=depth and gt=batch ["depth_gt"], and a1_pp is calculated by pred=depth_pp and gt=batch ["depth_gt"]. But I don't know how a1_gt and a1_gt are calculated. Could you please help me point out the program for these two parameters.

**Comment by zsh1223** [comment]
if use_gt_scale:
            pred_i = pred_i * torch.median(gt_i) / torch.median(pred_i)

**Comment by zsh1223** [comment]
I know now, _gt and pp_gt represent that the predicted depth map has undergone median scaling. So, in the final evaluation, we used the standard of<pp_gt. Is my understanding correct?

**Comment by sgasperini** [comment]
`gt` is for the median scaled predictions. `pp` is for those that are evaluated both normal and flipped (post-processed).

I do not fully understand your question.

If you ask about which of normal, `pp`, `gt`, `pp_gt` we report, that depends on the method being evaluated. This is also described in issue #8, I copy below the relevant part:

> for those models that are not scale-aware (indicated by a * in Tables 1 and 2 of the paper, e.g., Monodepth2), we apply the necessary ground truth scaling on top, so we report pp_gt for such methods. For example, we do not use gt scaling for ours because ours has the advantage of being scale-aware thanks to the weak velocity supervision introduced by PackNet-SfM, so for md4all, we report pp.

We hope this helps. If not, please clarify your question.

**Comment by zsh1223** [comment]
Thanks for your prompt and detailed reply! I am closing this issue.
