### ISSUE TITLE
About photometric_loss

### ISSUE THREAD

**Issue by zsh1223** [md4all/md4all#28]
I noticed that you did not use automask when calculating photometrics loss. And you have calculated two photometrics loss: ① the original image and the distorted ② original image and itself after pose transformation.  I don't quite understand why we need to calculate the photometric loss of the original image and itself.
![image](https://github.com/md4all/md4all/assets/130481211/02c978e4-6130-433a-9c1b-2db34f7118af)

**Comment by morbi25** [comment]
Hi @zsh1223,

As described in the [Monodepth2 paper](https://arxiv.org/pdf/1806.01260), the auto-masking approach "filters out pixels which do not change appearance from one frame to the next in the sequence." The code section that you attached **implicitly** computes the auto-masking technique in combination with the photometric losses appended before and the line [here](https://github.com/md4all/md4all/blob/1cb9300fc08d4a44d1f1d8faea96f0d4ca5bb1dc/losses/MultiViewPhotometricLoss.py#L205) (please see also [this issue](https://github.com/nianticlabs/monodepth2/issues/264) in the monodepth2 repository for more details).

We hope that helps!
