### ISSUE TITLE
Data loading issues

### ISSUE THREAD

**Issue by cdbhjac** [md4all/md4all#29]
Hi, can you please tell me, in loading the training is Database version not found
assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: \mnt\data\nuscenes\trainval\v1.0-trainval

**Comment by morbi25** [comment]
Hi @cdbhjac,

with the few information provided, it is difficult to guess what is going wrong. However, it seems that the dataset is not located in the respective directory.
- If you use our docker image, please ensure to adapt [line 26](https://github.com/md4all/md4all/blob/1cb9300fc08d4a44d1f1d8faea96f0d4ca5bb1dc/Makefile#L26), [line 33](https://github.com/md4all/md4all/blob/1cb9300fc08d4a44d1f1d8faea96f0d4ca5bb1dc/Makefile#L33), and [line 34](https://github.com/md4all/md4all/blob/1cb9300fc08d4a44d1f1d8faea96f0d4ca5bb1dc/Makefile#L34) of our Makefile accordingly.
- If you use the conda environment, please make sure to modify the DATASET.DATAROOT configuration parameter such that it points to the location of the nuScenes dataset on your local machine.

I hope this helps to resolve your problem. :)

Best regards,
Nils
