### ISSUE TITLE
About md4all AD

### ISSUE THREAD

**Issue by zsh1223** [md4all/md4all#33]
How to train md4all AD, please tell me how to train it?

**Comment by morbi25** [comment]
Hi @zsh1223,

Thank you for reaching out!

To train our md4allADa, e.g., on nuScenes, you can use the attached configuration file:
[train_md4allADa_nuscenes.txt](https://github.com/user-attachments/files/16049425/train_md4allADa_nuscenes.txt)

Please make sure to change the file extension to .yaml. I had to change it to .txt as GitHub does not accept .yaml files as attachments.

I hope that helps you. :)

Best regards,
Nils

**Comment by zsh1223** [comment]
Thank you for your reply. Could you please provide the evaluation file for md4allADa, e.g., on nuScenes. be deeply grateful.

**Comment by morbi25** [comment]
Hi @zsh1223,

Here is an exemplary configuration file for md4allADa evaluation; please adapt the configuration parameters according to your local environment:
[eval_md4all_ADa_80m_nuscenes_val.txt](https://github.com/user-attachments/files/16067584/eval_md4all_ADa_80m_nuscenes_val.txt)

Best regards,
Nils

**Comment by zsh1223** [comment]
Can you provide a pre trained weight for md4all AD? Thank you very much

**Comment by morbi25** [comment]
Hi,

I uploaded the checkpoints just now. :)

Best regards,
Nils
