### ISSUE TITLE
About ForkGAN training

### ISSUE THREAD

**Issue by KuonjiAlice514** [md4all/md4all#38]
Thank you very much for your work! I would like to ask you what are the parameters you use when training forkgan, especially image size and normalization (it would be nice if you could provide all of them). I have not been able to reproduce it well .

**Comment by morbi25** [comment]
Hi @KuonjiAlice514,

Thank you for reaching out!

I attached [one examplary configuration file](https://github.com/user-attachments/files/16423668/forkgan_options.txt) that we used during our training. We resized the images for nuScenes and RobotCar to 576x320 and 544x320, respectively, and used the normalization specified in the code.

I hope that this helps you!

Best regards,
Nils

**Comment by KuonjiAlice514** [comment]
> Hi @KuonjiAlice514,
> 
> Thank you for reaching out!
> 
> I attached [one examplary configuration file](https://github.com/user-attachments/files/16423668/forkgan_options.txt) that we used during our training. We resized the images for nuScenes and RobotCar to 576x320 and 544x320, respectively, and used the normalization specified in the code.
> 
> I hope that this helps you!
> 
> Best regards, Nils

Thank you very much for your help! It looks like you are using two parameters load_height and load_width when loading the image that the original code doesn't have. could you please share the code where you are using these two parameters?

**Comment by morbi25** [comment]
Hi @KuonjiAlice514,

We use load_width and load_height in the get_transform function (defined in base_dataset.py) to resize the images for nuScenes and RobotCar to 576x320 and 544x320, respectively, to approximately keep the original aspect ratio. You can do this by replacing the load_size with the load_width and load_height config parameters, such that:
```python
if 'resize' in opt.preprocess:
    osize = [opt.load_height, opt.load_width]
    transform_list.append(transforms.Resize(osize, method))
```

I hope this helps you! :)

Best regards,
Nils

**Comment by KuonjiAlice514** [comment]
Thank you very much for your help！
