### ISSUE TITLE
About evaluation

### ISSUE THREAD

**Issue by wangch-g** [md4all/md4all#39]
Hello, thanks for your interesting work!
Recently, I am trying to reproduce the results on nusecenes dataset. But I got some strange results. I used the command "python evaluation/evaluate_depth.py --config ./config/eval_md4allDDa_80m_nuscenes_val.yaml" to evaluate the checkpoint "md4allDDa_nuscenes.ckpt" that you provided.
Here is the results I got, have you ever seen this before?
[eval-md4allDDa-80m-nuscenes-val_result_metrics.csv](https://github.com/user-attachments/files/16947010/eval-md4allDDa-80m-nuscenes-val_result_metrics.csv)
I am looking forward to your reply, thank you very much!

**Comment by wangch-g** [comment]
I got it!
I used the early version of pytorch_lighting, so the checkpoint weight can not be loaded using the original code.
I added the loading code in the "evaluate_depth.py", and then got the correct results.

**Comment by sgasperini** [comment]
Hi @wangch-g,
It's great to hear you already resolved the issue! Thanks for the update and best regards.
Stefano
