### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by ygjwd12345** [md4all/md4all#4]
The registers on the RobotCar website don't work. Would you mind to share you RobotCar?

**Comment by sgasperini** [comment]
Hi @ygjwd12345, do you mean the original RobotCar dataset? It seems to work now (see https://robotcar-dataset.robots.ox.ac.uk/downloads/). The RobotCar website is a bit unstable, but eventually it works again. Let us know if you manage to download the data, or we can find another solution.

**Comment by ygjwd12345** [comment]
I have tried my Chinese official email and asked my Italian colleague for help. Unfortunately, the results are the same: the account can be registered successfully but the system tells me the account is inactivated when I download the dataset.

**Comment by sgasperini** [comment]
How urgent is it? Are you submitting to ICRA today?
I'm not sure it's legal for us to upload their data without consent

**Comment by ygjwd12345** [comment]
It is not a urgent issue. I can wait until you are available. 
In my opinion, it is fine for uncommercial use.
I'm an AP in a Chinese university.  I ask this data only to reproduce.

**Comment by sgasperini** [comment]
I'll write you an email

**Comment by sgasperini** [comment]
Hi @ygjwd12345 , I suggest contacting the data owners directly at [robotcardataset@robots.ox.ac.uk](mailto:robotcardataset@robots.ox.ac.uk) to help resolve this. Please consider their dataset does not belong to us, and we are not responsible for malfunctions of their website.
Thank you for your understanding and your interest in our work.

**Comment by ygjwd12345** [comment]
RobotCar finally made my account activate which is super delay I have faced.

**Comment by sgasperini** [comment]
Ok, glad it's finally resolved!
Let us know if you have any questions on our data/method.
