### ISSUE TITLE
test

### ISSUE THREAD

**Issue by MikalWu** [md4all/md4all#5]
pointcloud_dir = os.path.join(dataroot, scene, "lms_front_synchronized/vo/time_margin=+-4.0e+06", timestamp)
        pointcloud_path = f"{pointcloud_dir}.pcd.bin"       in robotcar_dataset.py

Hello, I can't find a way to download this file when doing the test, can you help? Thank you!

**Comment by morbi25** [comment]
Hello @MikalWu,

Thanks for reaching out.

Yes, we decided not to upload the projected point clouds. However, as also described in the README under Datasets->RobotCar in step 5, you can precompute the ground truth depth data on your own using our provided script data/robotcar/precompute_depth_gt.py.

If you face any problems while doing so, feel free to contact us again.

**Comment by morbi25** [comment]
Closed due to inactivity.
